# Generated by Django 5.2.7 on 2025-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('sqm_price', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'properties',
            },
        ),
    ]
